# Generated by Django 2.2.16 on 2022-09-24 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_auto_20220923_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(through='recipes.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
