# Generated by Django 2.2.16 on 2022-09-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
